project:
  type: book
  output-dir: docs 

book:
  title: "R4EnvChemAnalysis - PhD Course"
  author: "Victoria Eriksson"
  date: "2024-02-09"
  chapters:
    - index.qmd
    - Basics.qmd
    - Data_vis.qmd
    - qc_hdmse_peak.qmd
    - project.qmd
    - raw_ims_hrms.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

