project:
  type: book

book:
  title: "R4EnvChemAnalysis - PhD Course"
  author: "Victoria Eriksson"
  date: "2024-02-09"
  chapters:
    - index.qmd
    - Basics.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

