# NMCT-project

```{r}
#| output: false
library(tidyverse)
library(readxl)
```

```{r}
#it adds "decimals" to the data??? ############# "script out of bounds"
stdB_10ppb <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
                         sheet = "StD_10_240319",
                          na = "-")
stdB_10ppb|> 
  mutate(DT_average= mean(c(`DT...11`,`DT...20`,`DT...28`),na.rm = TRUE))

stdB_50ppb <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
    sheet = "StD_50_240319", skip = 1)
stdB_100ppb <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
    sheet = "StD_100_240319", skip = 1)
stdB_300ppb <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
    sheet = "StD_300_240319", skip = 1)
stdB_500ppb <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
    sheet = "StD_500_240319", skip = 1)

stdB_theor <- read_excel("~/Project/NM-CT-stdAB-240315/Norman CT StdMixB-DATACOMPARISON.xlsx", 
    range = "A1:H22")
```

```{r}
stdB_aminobenzothiazole <- stdB_theor |> 
  filter(`Item name` == "2-aminobenzothiazole") |> 
  inner_join(stdB_10ppb,join_by("2-aminobenzothiazole")
```
